### ISSUE TITLE
Unable to Download model

### ISSUE THREAD

**Issue by raghavgurbaxani** [ZhangMingliangAI/EAST-Pytorch#3]
Hi authors

Thank you for your great work on this repository. I am unable to download your model from Baidu though. 

Could you please perhaps provide a google drive link ? 

thanks.

**Comment by ZhangMingliangAI** [comment]
I'm sorry I just noticed it. The file of README has updated which provides Google drive link for your requirement.

**Comment by raghavgurbaxani** [comment]
hi @ZhangMingliangAI 
I have requested for pretrained model access, could you please provide it. Thanks

**Comment by ZhangMingliangAI** [comment]
@raghavgurbaxani The pretrained models have been provided in Google drive. Can't you download it?

**Comment by raghavgurbaxani** [comment]
@ZhangMingliangAI  here's what it says when I try to access via google drive - 

![image](https://user-images.githubusercontent.com/32988039/85950008-f50a6000-b90e-11ea-8b09-cedf4a8e0fb8.png)

Could you please provide access ? Thanks ..

**Comment by ZhangMingliangAI** [comment]
@raghavgurbaxani Models can be downloaded now.

**Comment by raghavgurbaxani** [comment]
Thanks @ZhangMingliangAI , closing this issue.
